# Generated by Django 4.2 on 2025-03-04 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_city_customuser_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
