# Generated by Django 4.2 on 2025-05-30 15:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('diagnosis', models.TextField()),
                ('treatment', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('follow_up', 'Needs Follow-up'), ('referred', 'Referred to Specialist')], default='active', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(choices=[('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('neurology', 'Neurology'), ('orthopedics', 'Orthopedics'), ('pediatrics', 'Pediatrics'), ('psychiatry', 'Psychiatry'), ('pulmonology', 'Pulmonology'), ('rheumatology', 'Rheumatology')], max_length=50)),
                ('doctor_name', models.CharField(max_length=100)),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=20)),
                ('appointment_date', models.DateField()),
                ('time_slot', models.CharField(choices=[('09:00', '09:00 AM - 09:30 AM'), ('09:30', '09:30 AM - 10:00 AM'), ('10:00', '10:00 AM - 10:30 AM'), ('10:30', '10:30 AM - 11:00 AM'), ('11:00', '11:00 AM - 11:30 AM'), ('11:30', '11:30 AM - 12:00 PM'), ('14:00', '02:00 PM - 02:30 PM'), ('14:30', '02:30 PM - 03:00 PM'), ('15:00', '03:00 PM - 03:30 PM'), ('15:30', '03:30 PM - 04:00 PM'), ('16:00', '04:00 PM - 04:30 PM'), ('16:30', '04:30 PM - 05:00 PM')], max_length=5)),
                ('appointment_type', models.CharField(choices=[('consultation', 'General Consultation'), ('follow-up', 'Follow-up'), ('new-patient', 'New Patient'), ('urgent', 'Urgent Care'), ('routine-checkup', 'Routine Checkup'), ('test-results', 'Test Results Review')], max_length=20)),
                ('appointment_mediums', models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], default='Physical', max_length=20)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('rescheduled', 'Rescheduled'), ('no-show', 'No Show')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('main_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['appointment_date', 'time_slot'],
                'unique_together': {('doctor_name', 'appointment_date', 'time_slot')},
            },
        ),
    ]
