# Generated by Django 4.2 on 2025-04-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_mediums',
            field=models.CharField(choices=[('Physical', 'Physical'), ('Online', 'Online')], default='Physical', max_length=20),
        ),
    ]
