# Generated by Django 4.2 on 2025-04-27 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_doctor_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(choices=[('Doctor2', 'Doctor2'), ('Doctor1', 'Doctor1'), ('Doctor3', 'Doctor3')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Doctor',
        ),
    ]
