# Generated by Django 4.2 on 2025-04-29 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(choices=[('NewDoctor', 'NewDoctor'), ('drbrown', 'drbrown'), ('Doctor3', 'Doctor3'), ('Doctor2', 'Doctor2'), ('Doctor1', 'Doctor1')], max_length=100),
        ),
    ]
